### ISSUE TITLE
Given Header Name find cell value for a row

### ISSUE THREAD

**Issue by sumxyz** [SheetJS/js-xls#109]
How can I get E5 cell value by giving E1 header name?

**Comment by reviewher** [comment]
@sumxyz you can convert to a JSON object using the `sheet_to_json` helper.

As an example, suppose your file was

```
a	b	c	d	e
1	2	3	4	5
10	9	8	7	6
11	12	13	14	15
20	19	18	17	16
```

You want to get cell E5 (which is 16) given the header in E1 (e).  `sheet_to_json` will give you an array of objects:

```js
> var XLS = require('xlsjs'); // only needed in node
> var wb = XLS.readFile('test.xls'); // use read or something else 
> XLS.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]])
[ { a: '1', b: '2', c: '3', d: '4', e: '5' },
  { a: '10', b: '9', c: '8', d: '7', e: '6' },
  { a: '11', b: '12', c: '13', d: '14', e: '15' },
  { a: '20', b: '19', c: '18', d: '17', e: '16' } ]
```

Assuming you want E5, it would be in the fourth row:

```js
> XLS.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]])[3]['e']
'16'
```

If you need the raw value rather than the formatted text, set the option `raw:true`:

```js
> XLS.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], {raw:true})[3]['e']
16
```

**Comment by reviewher** [comment]
@sumxyz we have merged the xls parsing logic into [js-xlsx](https://github.com/SheetJS/js-xlsx/) -- please raise a new issue there if you are still having issues.  js-xlsx is a drop-in replacement for js-xls.
