### ISSUE TITLE
excel read error when first row of a column is an empty cell.

### ISSUE THREAD

**Issue by kaustuv** [SheetJS/js-xls#59]
If excel data has a column whose value is an empty cell in the first row, then that column is not imported. This is possibly because utils.sheet_to_row_object_array() only has keys for non-empty cells.

This means that a simple example like this:

id col1 col2 col3
1 hello1 10
2 hello2 2 20
3 hello3 3 30

Only imports col1 and col3 correctly but not col2

**Comment by SheetJSDev** [comment]
@kaustuv if I understand correctly, using a CSV example:

```
a,b,,d,e,f
1,2,3,4,5,6
```

The third column is lost because the "header row" has no value.

This is by design, since there is no good answer to "what label should the parser use for that column", and there are a few ways to work around it.  The easiest one is to use the sheet_to_json method with the option `header:1` set.  This will give you an array of arrays that you can work with.  For the aforementioned example, you would get something like

```
[
    ["a","b",,"d","e","f"]
    [1,2,3,4,5,6]
]
```
