### ISSUE TITLE
program crashes when trying to read an empty cell

### ISSUE THREAD

**Issue by dgotlib** [SheetJS/js-xls#78]
I get "TypeError: cannot read property 'v' of undefined.

**Comment by SheetJSDev** [comment]
@dgotlib sorry for the belated reply!  If you can share a code sample and a file, I can take a look, but using the standard utilities this should never happen.

By default, empty cells (as in, ones with no content) are not generated.  This is an intentional decision, mainly because it would greatly increase the size of the representation of sparse documents (which is relevant when working in a Web Worker context, since you have to serialize before sending data between the main execution thread and the worker thread).

The utility functions have guards to make sure cells exist before being read.  For example, the sheet_to_csv function tests for cell validity before proceeding: https://github.com/SheetJS/js-xls/blob/master/bits/90_utils.js#L147-L148

**Comment by dgotlib** [comment]
Thanks for the reply.
I worked around the problem by using the code that converts the spreadsheet
to CSV,
and then worked with the CSV only.
Great utility!
Thanks
Dvid

**Comment by afbruno** [comment]
It happens because of line 7290:
Here is the problem. --> if(val === undefined || val.t === undefined) continue;
v = val.v;
		switch(val.t){
					case 'e': continue;
					case 's': break;
					case 'b': case 'n': break;
					default: throw 'unrecognized type ' + val.t;
				}
				if(v !== undefined) {
					row[hdr[C]] = raw ? v : format_cell(val,v);
					isempty = false;
				}
So I replaced it by:
if(val === undefined || val.t === undefined){
				row[hdr[C]] = "";
				isempty = false;
			}else{
				v = val.v;
				switch(val.t){
					case 'e': continue;
					case 's': break;
					case 'b': case 'n': break;
					default: throw 'unrecognized type ' + val.t;
				}
				if(v !== undefined) {
					row[hdr[C]] = raw ? v : format_cell(val,v);
					isempty = false;
				}
			}

Worked perfectly. 
Att,

**Comment by dgotlib** [comment]
thanks
david

**Comment by reviewher** [comment]
@afbruno I'm not sure how that change addresses the problem.  If `val` were undefined when `val.v` was read, the existing guard should have taken effect.

Either way, we have made some changes after merging this library into [js-xlsx](https://github.com/SheetJS/js-xlsx/) -- we encourage everyone to upgrade as it is a drop-in replacement and has support for additional formats like XLSX.

@afbruno and @dgotlib if you have any test files we would love to take a look!
