### ISSUE TITLE
How to handle dates?

### ISSUE THREAD

**Issue by brunano21** [SheetJS/js-xls#82]
Hi,

I'm parsing an excel file, that may contain a date in a cell.
I get the content of the cell with the follow:

```
var cell_ref = XLS.utils.encode_cell({c:C,r:R});
cell_value = workbook.Sheets[sheet_name_list[0]][cell_ref].v;
```

The problem is that a date like `01/01/1950` is converted into `18264`. However, I'm interested in getting only a **_simple string**_. I tried `.w` but I got a `01/01/50`.
Any help?
Thanks.

**Comment by brunano21** [comment]
Little update:
If I use `var data = XLS.utils.sheet_to_json(sheet, {header:1});` the date string I get is `01/01/50`, I would like to have `01/01/1950` instead.

**Comment by janvanderhaegen** [comment]
I ran into the same issue. 
For future reference, find the object creation
```
var table_fmt = {
            0: 'General',
            1: '0',
            //etc
```

Number 14 seems to define the format used when parsing XLSX cells that are stored in the date format. Change it from m/d/yy to mm/dd/yyyy (or whatever fits your needs).

**Comment by SheetJSDev** [comment]
@janvanderhaegen the problem is that format code 14 is based on the client locale.  The file doesn't tell you the locale of the computer that saves the file, so depending on your localization settings you will see something different.  See https://github.com/SheetJS/js-xlsx/issues/560 for a related issue.

Please migrate to js-xlsx -- it replicates the entire js-xls API, including exporting the XLS variable in browser.
