### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by Sulexa** [SheetJS/js-xls#88]
Hi, i try to read a xls file which have 12 sheet composed of 50 column by 7000 row (I can't share this file). Actually i have a out of memory error so there is a way for read only one sheet at the time?(like that everytime i read a new sheet i delete the previous one)
My application is client-side, did the node js version could avoid that problem?
thanks for help

**Comment by reviewher** [comment]
Without sharing the file, it's unclear where the problem lies.  Most XLS files nowadays are wrapped in a [CFB container](https://en.wikipedia.org/wiki/Compound_File_Binary_Format), so the parser has to first understand how the container is represented.  Thanks to some technically-valid-but-not-that-great file writers (see https://github.com/PHPOffice/PHPExcel/issues/260#issuecomment-61432748 for an example) we have to load the entire file first.  Once you do that, then you have to read the Workbook stream and collect relevant metadata before touching a cell.  Especially in a constrained browser environment like IE6, it's easy to quickly overrun limits on modest files.

We have merged this library into the [XLSX library](https://github.com/SheetJS/js-xlsx) -- we recommend upgrading.  If you have a file that you can share, please re-raise the issue in that issue tracker with a file.
