### ISSUE TITLE
Zero value with [h]:mm format is incorrectly formatted by sheet_to_csv

### ISSUE THREAD

**Issue by tedbeer** [SheetJS/js-xls#98]
sheet_to_csv uses format_cell to format values. It incorrectly process 0 value when '[h]:mm' format is applied.
format_cell({v: 0, t: 'n', z: '[h]:mm'}) returns '0:01'
In Excel the cell is correctly shown as '0:00'

**Comment by tedbeer** [comment]
If format is  '[h]:mm:ss' the cell is formatted correctly to '0:00:00'

**Comment by reviewher** [comment]
This is an issue for the formatting library https://github.com/SheetJS/ssf/ -- I copied the issue over there.

**Comment by SheetJSDev** [comment]
For reference, the `mm` was improperly detected as a month rather than minute (gotta love how excel uses the character to potentially refer to either month or minute).  The logic looked to see if a series of `m` characters was preceded by an hour token or proceeded by a second token but did not properly consider absolute times as tokens.  This was fixed in ssf 0.9.2 and will be bubbled into xlsx in the next release
